### ISSUE TITLE
Create ARDUINO 2 code

### ISSUE THREAD

**Issue by Saishf** [Saishf/Automated-Greenhouse#2]
Create a Arduino 2 code for controlling water pumps for irrigation and humidity inside the greenhouse after taking input from the soil moisture sensors and the DHT11 sensor.

**Comment by Saishf** [comment]
Would like to work on this as well, please do assign it to me!

**Comment by ashishfargade** [comment]
Would like to work on this as well, please do assign it to me!

**Comment by Saishf** [comment]
Assigning it to you, good luck!
